# Generated by Django 5.2.6 on 2025-09-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockHat', '0003_alter_scheduledtask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
