# Generated by Django 5.2.6 on 2025-09-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockHat', '0003_useragentdescktop_useragentmobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAgentDescktop',
            new_name='UserAgentDesktop',
        ),
    ]
