# Generated by Django 5.2.6 on 2025-09-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockHat', '0004_rename_useragentdescktop_useragentdesktop'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='referer',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
