# Generated by Django 5.2.6 on 2025-09-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockHat', '0006_requestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
