# Generated by Django 5.2.6 on 2025-09-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockHat', '0007_taskstatus_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
